export const USERS_MESSAGES = {
  VALIDATION_ERROR: 'Lỗi xác thực',
  NAME_IS_REQUIRED: 'Vui lòng nhập tên',
  NAME_MUST_BE_A_STRING: 'Tên phải là một chuỗi ký tự',
  NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Tên phải có độ dài từ 1 đến 100 ký tự',
  EMAIL_ALREADY_EXISTS: 'Email đã tồn tại',
  EMAIL_IS_REQUIRED: 'Vui lòng nhập email',
  EMAIL_IS_INVALID: 'Email không hợp lệ',
  PASSWORD_IS_REQUIRED: 'Vui lòng nhập mật khẩu',
  PASSWORD_MUST_BE_A_STRING: 'Mật khẩu phải là một chuỗi ký tự',
  PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50: 'Mật khẩu phải có độ dài từ 6 đến 50 ký tự',
  PASSWORD_MUST_BE_STRONG: 'Mật khẩu phải có chữ hoa, chữ thường, số và ký tự đặc biệt',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Vui lòng nhập lại mật khẩu',
  CONFIRM_PASSWORD_MUST_BE_A_STRING: 'Mật khẩu xác nhận phải là một chuỗi ký tự',
  CONFIRM_PASSWORD_DOES_NOT_MATCH: 'Mật khẩu xác nhận không khớp',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50: 'Mật khẩu xác nhận phải có độ dài từ 6 đến 50 ký tự',
  CONFIRM_PASSWORD_MUST_BE_STRONG: 'Mật khẩu xác nhận phải có chữ hoa, chữ thường, số và ký tự đặc biệt',
  DATE_OF_BIRTH_MUST_BE_ISO8601: 'Ngày sinh phải đúng định dạng ISO8601',

  USER_NOT_FOUND: 'Tài khoản không tồn tại',
  LOGIN_SUCCESS: 'Đăng nhập thành công',
  REGISTER_SUCCESS: 'Đăng ký thành công',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token là bắt buộc',
  ACCESS_TOKEN_IS_INVALID: 'Access token không hợp lệ',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token là bắt buộc',
  REFRESH_TOKEN_IS_INVALID: 'Refresh token không hợp lệ',
  REFRESH_TOKEN_NOT_FOUND_AND_ALREADY_USED: 'Refresh token không tồn tại hoặc đã được sử dụng',
  LOGOUT_SUCCESS: 'Đăng xuất thành công',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Vui lòng cung cấp mã xác thực email',
  EMAIL_ALREADY_VERIFIED_BEFORE: 'Email đã được xác minh trước đó',
  EMAIL_VERIFY_SUCCESS: 'Xác minh email thành công',
  RESEND_VERIFY_EMAIL_SUCCESS: 'Gửi lại email xác thực thành công',
  CHECK_EMAIL_T0_RESET_PASSWORD: 'Vui lòng kiểm tra email của bạn',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Vui lòng cung cấp token để đặt lại mật khẩu',
  FORGOT_PASSWORD_TOKEN_IS_INVALID: 'Token đặt lại mật khẩu không hợp lệ',
  VERIFY_FORGOT_PASSWORD_SUCCESS: 'Xác thực token quên mật khẩu thành công',
  RESET_PASSWORD_SUCCESS: 'Đặt lại mật khẩu thành công',
  GET_ME_SUCCESS: 'Lấy thông tin người dùng thành công',
  USER_NOT_VERIFED: 'Người dùng chưa xác thực tài khoản',
  BIO_MUST_BE_STRING: 'Bio phải là một cuỗi kí tự hoặc liên kết',
  BIO_LENGTH_MUST_BE_FROM_1_TO_255: 'Bio phải có độ dài từ 1 đến 255 ký tự',
  LOCATION_MUST_BE_STRING: 'Location phải là một chuỗi kí tự',
  LOCATION_LENGTH_MUST_BE_FROM_1_TO_255: 'Location phải có độ dài từ 1 đến 255 ký tự',
  WEBSITE_MUST_BE_STRING: 'Website phải là một chuỗi kí tự',
  WEBSITE_LENGTH_MUST_BE_FROM_1_TO_150: 'Website phải có độ dài từ 1 đến 150 ký tự',
  USERNAME_MUST_BE_STRING: 'Username phải là một chuỗi kí tự',
  USERNAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Username phải có độ dài từ 1 đến 100 ký tự',
  IMAGE_URL_MUST_BE_STRING: 'Hình ảnh phải là một chuỗi kí tự',
  IMAGE_URL_LENGTH_MUST_BE_FROM_1_TO_400: 'Hình ảnh phải có độ dài từ 1 đến 400 ký tự',
  UPDATE_PROFILE_SUCCESS: 'Cập nhật thông tin người dùng thành công',
  FOLLOWER_SUCCESS: 'Follow thành công',
  INVALID_USER_USER_ID: 'ID người dùng không đúng định dạng',
  FOLLOWED: 'Bạn đã follow người dùng này',
  UNFOLLOWER_SUCCESS: 'Bạn đã unfollow thành công',
  GET_PROFILE_SUCCESS: 'Thông tin người dùng',
  USERNAME_INVALID:
    'Tên người dùng không hợp lệ. Phải từ 4 đến 15 ký tự, chỉ gồm chữ cái, số, dấu gạch dưới, và không được chỉ toàn là số.',

  USERNAME_EXISTED: 'Tên người dùng đã tồn tại. Vui lòng nhập lại',
  OLD_PASSWORD_NOT_MATCH: 'Mật khẩu cũ không đúng',
  CHANGE_PASSWORD_SUCCESS: 'Cập nhật mật khẩu thành công',
  GMAIL_NOT_VERIFIED: 'Tài khoản gmail chưa được xác thực',
  UPLOAD_SUCCESS: 'Tải ảnh/video thành công',
  REFRESH_TOKEN_SUCCESS: 'Refresh_token thành công',
  GET_VIDEO_STATUS_SUCCESS: 'lấy trạng thái video thành công'
} as const

export const TWEETS_MESSAGES = {
  INVALID_TYPE: 'Type không hợp lệ',
  INVALID_AUDIENCE: 'Audience không hợp lệ',
  PARENT_ID_MUST_BE_A_VALID_TWEET_ID: 'Id tweets phải là id của tweet cha',
  PARENT_ID_MUST_BE_NULL: 'Id tweets bắt buộc là null',
  CONTENT_MUST_BE_A_NON_EMPTY_STRING: 'Nội dung không được rỗng',
  CONTENT_MUST_BE_EMPTY_STRING: 'Nội dung bắt buộc phải rỗng',
  HASHTAGS_MUST_BE_AN_ARRAY_OF_STRING: 'Mỗi phần tử trong mảng là string',
  MENTIONS_MUST_BE_AN_ARRAY_OF_USER_ID: 'Mỗi phần tử trong mảng là user_id',
  MEDIAS_MUST_BE_AN_ARRAY_OF_MEDIA_OBJECT: 'Medias phải là mảng bao gồm url và kiểu của media'
} as const

export const COMMENTS_MESSAGES = {
  BOOKMARK_SUCCESS: 'Bookmark tweet thành công',
  UNBOOKMARK_SUCCESS: 'UnBookmark tweet thành công',
  LIKE_SUCCESS: 'Like tweet thành công',
  UNLIKE_SUCCESS: 'UnLike tweet thành công'
} as const
